name: ergodicity
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.3
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bleach=3.3.0
  - brotlipy=0.7.0
  - ca-certificates=2020.10.14
  - certifi=2021.5.30
  - cffi=1.14.5
  - chardet=4.0.0
  - cryptography=3.4.7
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=5.0.7
  - defusedxml=0.7.1
  - deprecation=2.1.0
  - entrypoints=0.3
  - expat=2.3.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.68.1
  - glib-tools=2.68.1
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - icu=68.1
  - idna=2.10
  - importlib-metadata=4.0.1
  - intel-openmp=2021.2.0
  - ipykernel=5.5.3
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=2.11.3
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-packaging=0.9.2
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.6.4
  - jupyterlab=3.0.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.4.0
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libclang=11.1.0
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.3.0
  - libglib=2.68.1
  - libgomp=9.3.0
  - libiconv=1.16
  - libllvm11=11.1.0
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.2
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib=3.4.1
  - matplotlib-base=3.4.1
  - mistune=0.8.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - mysql-common=8.0.23
  - mysql-libs=8.0.23
  - nbclassic=0.2.7
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.3.0
  - nspr=4.30
  - nss=3.64
  - numpy=1.20.1
  - numpy-base=1.20.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.4
  - pandoc=2.12
  - pandocfilters=1.4.2
  - parso=0.8.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.2
  - pip=21.1
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.18
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.8.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.2
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2021.1
  - pyzmq=22.0.3
  - qt=5.12.9
  - readline=8.1
  - requests=2.25.1
  - scipy=1.6.2
  - seaborn=0.11.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - sniffio=1.2.0
  - sqlite=3.35.5
  - terminado=0.9.4
  - testpath=0.4.4
  - tk=8.6.10
  - tomlkit=0.7.0
  - tornado=6.1
  - tqdm=4.61.1
  - traitlets=5.0.5
  - tzdata=2021a
  - urllib3=1.26.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
